from artsy_tiled_image_downloader.config import (
    DEFAULT_CONCURRENCY,
    DEFAULT_METAPHYSICS_ENDPOINT,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_RETRIES,
    DEFAULT_TIMEOUT_SECONDS,
    GRAPHQL_HEADERS,
    IMAGE_HEADERS,
    REQUEST_HEADERS,
    DownloaderSettings,
)

REQUEST_TIMEOUT = DEFAULT_TIMEOUT_SECONDS
METAPHYSICS_ENDPOINT = DEFAULT_METAPHYSICS_ENDPOINT
FOLDER_PATH = str(DEFAULT_OUTPUT_DIR)
TEMP_IMGS_PATH = None
MAX_WORKERS = DEFAULT_CONCURRENCY
DOWNLOAD_RETRIES = DEFAULT_RETRIES

__all__ = [
    "DOWNLOAD_RETRIES",
    "FOLDER_PATH",
    "GRAPHQL_HEADERS",
    "IMAGE_HEADERS",
    "MAX_WORKERS",
    "METAPHYSICS_ENDPOINT",
    "REQUEST_HEADERS",
    "REQUEST_TIMEOUT",
    "TEMP_IMGS_PATH",
    "DownloaderSettings",
]
